---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus
    version: 8.9.0
  values:
    alertmanager:
      statefulSet:
        enabled: false
    server:
      statefulSet:
        enabled: true
